spring:
  application:
    name: product-service
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=product&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      mode: ALWAYS
      schema-locations: classpath:init-schema.sql

server:
    port: 8081

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  product-created-topic: product-created-topic
  category-created-topic: category-created-topic
